statistic:
  model:
    cron-expression: ${MODEL_STATISTIC_CRON_EXPRESSION:0 0 * ? * *}

app:
  feign:
    appery-io:
      url: https://api.appery.io/rest/1/db/collections
      api-key: ${APPERY_API_KEY:#{null}}
    faces:
      connect-timeout: ${CONNECTION_TIMEOUT:10000}
      read-timeout: ${READ_TIMEOUT:60000}
      retryer:
        max-attempts: ${MAX_ATTEMPTS:1}
    embedding:
      connect-timeout: ${EMBEDDING_CONNECTION_TIMEOUT:5000}
      read-timeout: ${EMBEDDING_READ_TIMEOUT:5000}
      retryer:
        max-attempts: ${EMBEDDING_MAX_ATTEMPTS:1}

---
