server:
  port: 8081

spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: mongo,mlCalculator,cache

---

spring:
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://msqv355.exadel.by:27017}
      database: recognition

---

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

